import "dotenv/config";
import "./database/index.js";
import express from "express";
import helmet from "helmet";
import session from "express-session";
import path from "path";
import passport from "./config/passport.js";
import MailService from "./services/mail.js";
import portalRoutes from "./routes/portal.routes.js";
import apiRoutes from "./routes/api.routes.js";
import adminApiRoutes from "./routes/admin.api.routes.js";
import adminPagesRoutes from "./routes/admin.pages.routes.js";
import taskManagementRoutes from "./routes/task-management.routes.js";
import worklogReportRoutes from "./routes/worklog-report.routes.js";
import overtimeApiRoutes from "./routes/overtime.api.routes.js";
import overtimePagesRoutes from "./routes/overtime.pages.routes.js";
import oncallApiRoutes from "./routes/oncall.api.routes.js";
import oncallPagesRoutes from "./routes/oncall.pages.routes.js";
import User from "./models/user.js";
import { loginLimiter, apiLimiter } from "./config/limiters.js";
if(!process.env.SECRET||process.env.SECRET.length<32){console.error("ERRO FATAL: SECRET ausente ou curta.");process.exit(1)}
const app=express(),isProd=process.env.NODE_ENV==="production",BASE_URL=process.env.BASE_URL||"http://localhost:5000";app.set("trust proxy",1);app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'","'unsafe-inline'","'unsafe-eval'","https://www.gstatic.com","https://www.google.com","https://apis.google.com"],styleSrc:["'self'","'unsafe-inline'","https://fonts.googleapis.com"],fontSrc:["'self'","https://fonts.gstatic.com"],imgSrc:["'self'","data:","https:"],connectSrc:["'self'"],frameSrc:["'none'"],objectSrc:["'none'"]}},crossOriginEmbedderPolicy:false}));app.use("/public",express.static("public"));app.use("/uploads",express.static("uploads"));app.set("view engine","ejs");app.set("views",path.join(__dirname,"views"));app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SECRET,resave:false,saveUninitialized:false,cookie:{maxAge:86400000,httpOnly:true,secure:isProd,sameSite:"lax"}}));app.use(passport.initialize());app.use(passport.session());app.get("/health",(q,s)=>s.json({status:"ok",timestamp:new Date().toISOString()}));app.use("/api",apiLimiter,apiRoutes);app.get("/",(q,s)=>q.session.adminUser||q.isAuthenticated()?s.redirect("/admin"):q.session.clientUser?s.redirect("/portal"):s.render("home"));
app.get("/admin/login",(q,s)=>{const m=q.session.messages||[];q.session.messages=[];s.render("admin/admin-login",{error:m[0]||null})});app.post("/admin/login",loginLimiter,async(q,s,n)=>{try{const u=await User.findOne({where:{email:q.body.email}});if(!u||!await u.checkPassword(q.body.password))return s.render("admin/admin-login",{error:"Email ou senha inválidos."});q.login(u,e=>{if(e)return n(e);q.session.adminUser=u.toJSON();q.session.activeGroup=null;q.session.save(x=>x?n(x):s.redirect("/admin"))})}catch(e){n(e)}});app.post("/admin/set-group",(q,s)=>{if(!q.session.adminUser&&!q.isAuthenticated())return s.sendStatus(401);q.session.activeGroup=!q.body.groupId||q.body.groupId==="null"?null:parseInt(q.body.groupId,10);q.session.save(e=>e?s.sendStatus(500):s.redirect(q.body.redirect||q.headers.referer||"/admin"))});
app.use("/api/admin/overtime",overtimeApiRoutes);app.use("/admin/overtime",overtimePagesRoutes);app.use("/admin/api/oncall",oncallApiRoutes);app.use("/admin",oncallPagesRoutes);app.use("/admin/api/tasks-management",taskManagementRoutes);app.use("/admin/reports/worklogs",worklogReportRoutes);app.use("/admin/api",adminApiRoutes);app.use("/admin",adminPagesRoutes);
app.get("/admin/auth/google",passport.authenticate("google-admin"));app.get("/admin/auth/google/callback",passport.authenticate("google-admin",{failureRedirect:"/admin/login",failureMessage:true}),(q,s)=>{q.session.adminUser=q.user.toJSON();q.session.activeGroup=null;q.session.save(()=>s.redirect("/admin"))});app.get("/admin/auth/microsoft",passport.authenticate("microsoft-admin"));app.get("/admin/auth/microsoft/callback",passport.authenticate("microsoft-admin",{failureRedirect:"/admin/login",failureMessage:true}),(q,s)=>{q.session.adminUser=q.user.toJSON();q.session.activeGroup=null;q.session.save(()=>s.redirect("/admin"))});app.get("/admin/logout",(q,s,n)=>q.logout(e=>{if(e)return n(e);q.session.destroy(()=>s.redirect("/admin/login"))}));app.use(portalRoutes);app.use((q,s)=>s.status(404).render("errors/404",{context:q.originalUrl.startsWith("/admin")?"admin":"portal"}));app.use((e,q,s,n)=>{console.error("Erro:",isProd?e.message:e.stack);s.status(500).render("errors/500")});async function start(){await MailService.initialize();app.listen(process.env.PORT||5000,()=>console.log(`Servidor iniciado: ${BASE_URL}`))}start();
